version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: eazytick
        container_name: eazytick-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - eazytick
        ports:
            - '8001:8000'

    db:
        image: mysql:8.0
        container_name: eazytick-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: eazytick
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - eazytick
        ports:
            - '3307:3306'

    nginx:
        image: nginx:alpine
        container_name: eazytick-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - eazytick

networks:
    eazytick:
        driver: bridge
